# yamllint disable rule:comments-indentation
---
###############################################################################
#  Very basic probably not secure Authelia Configration                       #
#  See configuration.template.yml for more details                            #
###############################################################################

host: 127.0.0.1
port: 9091

theme: light

server:
  read_buffer_size: 4096
  write_buffer_size: 4096
  path: ""
  enable_pprof: false
  enable_expvars: false

log:
  level: info
  file_path: /var/log/authelia/authelia.log

## set using a secret: https://www.authelia.com/docs/configuration/secrets.html
jwt_secret: JWT_SECRET

default_redirection_url: https://login.example.com

authentication_backend:
  disable_reset_password: true
  refresh_interval: 5m
  file:
    path: /etc/authelia/users.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny

  rules:
    - domain: "*.example.com"
      policy: one_factor

session:
  name: authelia_session

  domain: example.com
  same_site: lax
  secret: insecure_session_secret
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  local:
    path: /var/lib/authelia/db.sqlite3

notifier:
  disable_startup_check: false
  filesystem:
    filename: /var/lib/authelia/notification.txt
...
