#!/bin/sh

set -e

case "$1" in
  configure)
    if ! getent passwd git > /dev/null; then
       adduser --disabled-password --quiet --system --group \
          --home /var/git --no-create-home \
          --gecos "git user" --shell /bin/bash git
    fi
    if ! test -d /var/git/data
    then
       mkdir -p /var/git/data
    fi
    chown -R git:git /var/git
    chown git:git /etc/forgejo/app.ini
    if ! test -d /var/log/forgejo
    then
       mkdir /var/log/forgejo
    fi
    chown git:git /var/log/forgejo
    chown git:git /etc/forgejo/app.ini /etc/forgejo
    sed -i "s/127.0.0.1/$(hostname --fqdn)/" /etc/forgejo/app.ini
    if ! test -e /etc/forgejo/cert.pem; then
       cd /etc/forgejo
       su -s /bin/bash -c "/opt/forgejo/forgejo cert --host $(hostname --fqdn)" git
    fi
    systemctl enable forgejo
    systemctl start forgejo
  ;;
esac

exit 0
