#!/bin/sh
 
if test "$1" = "configure"; then
  # Create a pdnsadmin system group
  if ! getent group pdnsadmin > /dev/null; then
      addgroup --quiet --system pdnsadmin
  fi
  
  # Create a pdnsadmin system user
  if ! getent passwd pdnsadmin > /dev/null; then
      adduser --quiet --system           --ingroup pdnsadmin           --home /opt/powerdns-admin           --no-create-home           --disabled-password --shell /bin/false           pdnsadmin
      usermod -c "PowerDNS admin user" pdnsadmin
  fi

  test -d /var/lib/powerdns-admin || mkdir -p /var/lib/powerdns-admin

  chown -R pdnsadmin:pdnsadmin /var/lib/powerdns-admin
  systemd-tmpfiles --create

  if ! test -f /var/lib/powerdns-admin/pdns.db; then
     su -s /bin/bash pdnsadmin -c "cd /opt/powerdns-admin && . /etc/default/powerdns-admin; export FLASK_CONF FLASK_APP PYTHONPATH; PATH=/opt/powerdns-admin/bin:$PATH flask db init"
  fi
  su -s /bin/bash pdnsadmin -c "cd /opt/powerdns-admin && . /etc/default/powerdns-admin; export FLASK_CONF FLASK_APP PYTHONPATH; PATH=/opt/powerdns-admin/bin:$PATH flask db upgrade"

  systemctl enable powerdns-admin
  systemctl restart powerdns-admin
else
  systemctl restart powerdns-admin
fi
