#!/bin/sh

set -e

case "$1" in
  configure)
    if ! getent passwd git > /dev/null; then
       adduser --disabled-password --quiet --system --group \
          --home /var/git --no-create-home \
          --gecos "git user" --shell /bin/bash git
    fi
    if ! test -d /var/git/data
    then
       mkdir -p /var/git/data
    fi
    chown -R git:git /var/git
    chown git:git /etc/gitea/app.ini
    if ! test -d /var/log/gitea
    then
       mkdir /var/log/gitea
    fi
    chown git:git /var/log/gitea
    chown git:git /etc/gitea/app.ini /etc/gitea
    sed -i "s/127.0.0.1/$(hostname --fqdn)/" /etc/gitea/app.ini
    if ! test -e /etc/gitea/cert.pem; then
       cd /etc/gitea
       su -s /bin/bash -c "/opt/gitea/gitea cert --host $(hostname --fqdn)" git
    fi
    systemctl enable gitea
    systemctl start gitea
  ;;
esac

exit 0
