#!/bin/sh -e

if [ "$1" = "remove" ]; then
    dpkg-divert --package firefox-en --rename --remove /usr/bin/firefox
    dpkg-divert --package firefox-en --rename --remove /usr/bin/www-browser
    dpkg-divert --package firefox-en --rename --remove /usr/bin/x-www-browser
fi
