#!/bin/sh -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] ; then
    update-alternatives --install /usr/bin/x-www-browser \
        x-www-browser /opt/firefox/firefox 70
    update-alternatives --install /usr/bin/www-browser \
        www-browser /opt/firefox/firefox 70
    update-alternatives --install /usr/bin/firefox \
        firefox /opt/firefox/firefox 70
fi
