#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
    if getent passwd unbound >/dev/null; then
        if which deluser >/dev/null 2>&1; then
            deluser --quiet --system unbound || echo "Could not remove unbound user."
        fi
    fi
fi
