#!/bin/sh

set -e

umask 0022
ACTION="$1"
VERSION="$2"

if [ "$ACTION" = "configure" ]; then
	# add the node-red user
	if ! getent passwd node-red >/dev/null; then
		useradd --user-group --system --home-dir /var/lib/node-red node-red
	fi
	if ! test -d /var/lib/node-red
	then
		mkdir /var/lib/node-red
		chown node-red:node-red /var/lib/node-red
	fi
	systemctl enable node-red
fi

systemctl restart node-red
