#!/bin/sh
# postinst script for mosquitto
#
# see: dh_installdeb(1)

set -e

setup_mosquitto_user() {
   # Create a mosquitto system group
   if ! getent group mosquitto > /dev/null; then
       addgroup --quiet --system mosquitto
   fi

   if ! getent passwd mosquitto >/dev/null; then
      adduser --quiet --system --ingroup mosquitto --no-create-home --home /var/lib/mosquitto --shell /usr/sbin/nologin mosquitto
   fi
}

case "$1" in
configure)
   setup_mosquitto_user
   chown mosquitto:mosquitto /var/lib/mosquitto /var/log/mosquitto
   systemctl enable mosquitto
;;
abort-upgrade|abort-remove|abort-deconfigure)
;;

*)
   echo "postinst called with unknown argument \`$1'" >&2
   exit 1
;;
esac

systemctl restart mosquitto

exit 0
