#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
    systemctl stop termix 2>/dev/null || true
    if getent passwd termix >/dev/null; then
        if which deluser >/dev/null 2>&1; then
            deluser --quiet --system termix || echo "Could not remove termix user."
        fi
    fi
fi