#!/bin/sh
 
if test "$1" = "configure"; then
  # Create a hollama system group
  if ! getent group hollama > /dev/null; then
      addgroup --quiet --system hollama
  fi
  # Create a hollama system user
  if ! getent passwd hollama > /dev/null; then
      adduser --quiet --system \
          --home /opt/hollama \
          --no-create-home \
          --disabled-password --shell /bin/false \
          hollama
      usermod -c "hollama user" hollama
  fi

  systemctl enable hollama.service
  systemctl start hollama.service
else
  systemctl restart hollama.service
fi
