#!/bin/bash
 
if test "$1" = "configure"; then
   # Create a esphome system group
   if ! getent group esphome > /dev/null; then
       addgroup --quiet --system esphome
   fi
   
   # Create a esphome system user
   if ! getent passwd esphome > /dev/null; then
       adduser --quiet --system \
           --ingroup esphome \
           --home /var/lib/esphome \
           --disabled-password \
           esphome
       usermod -c "ESPHome user" esphome
   fi
   chown -R esphome:esphome /var/lib/esphome
   if ! test -e /etc/esphome/privkey.pem; then
      openssl req \
       -newkey rsa:2048 \
       -x509 \
       -nodes \
       -keyout /etc/esphome/fullchain.pem \
       -new \
       -out /etc/esphome/privkey.pem \
       -subj /CN=$(hostname --fqdn) \
       -reqexts SAN \
       -extensions SAN \
       -config <(cat /etc/ssl/openssl.cnf \
           <(printf '[SAN]\nsubjectAltName=DNS:'$(hostname --fqdn))) \
       -sha256 \
       -days 3650
   fi
fi
